workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - build
  - test

default:
  image: haskell:9.6.4

build:
  artifacts:
    paths:
      - compile
  needs: []
  script:
    - make
  stage: build

test:
  needs:
    - artifacts: false
      job: build
  script:
    - make check
  stage: test
