include:
  - template: Code-Quality.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - lint
  - build
  - test

default:
  image: haskell:9.6.3

.stack-cache:
  variables:
    STACK_ROOT: $CI_PROJECT_DIR/.stack
  before_script:
    - mkdir -p .stack
  cache:
    - key:
        files:
          - stack.yml
          - stack.yml.lock
      paths:
        - .stack-work/
        - .stack/
    - key:
        files:
          - wacc/package.yaml
          - wacc/wacc.cabal
      paths:
        - wacc/.stack-work/

lint:
  image:
    entrypoint: [""]
    name: ghcr.io/danieljtrowbridge/docker-fourmolu:9.6.4
  needs: []
  script:
    - fourmolu --mode check wacc
  stage: lint

build:
  artifacts:
    paths:
      - compile
  needs: []
  script:
    - make
  stage: build
  extends: .stack-cache

integration-test:
  script:
    - make integration-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  extends: .stack-cache

unit-test:
  script:
    - make unit-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  extends: .stack-cache
