variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none

include:
  - template: Code-Quality.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - lint
  - build
  - test

lint:
  tags:
    - shell
  script:
    - fourmolu --mode check wacc
  stage: lint

build:
  tags:
    - shell
  script:
    - make build-test
  stage: build

code_quality:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - docker
  services:            # Shut off Docker-in-Docker
  variables:
    GIT_SUBMODULE_STRATEGY: none

integration-test:
  tags:
    - shell
  script:
    - make integration-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

unit-test:
  tags:
    - shell
  script:
    - make unit-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

golden-test:
  tags:
    - shell
  script:
    - make golden-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
