variables:
  BUILD_CACHE_POLICY: 'pull'

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - lint
  - build
  - test

default:
  image: haskell:9.6.3

.stack-cache:
  variables:
    STACK_ROOT: $CI_PROJECT_DIR/.stack
  before_script:
    - mkdir -p .stack
  cache:
    - key:
        files:
          - stack.yml
          - stack.yml.lock
      paths:
        - .stack-work/
        - .stack/
      policy: $BUILD_CACHE_POLICY
    - key:
        files:
          - wacc/package.yaml
          - wacc/wacc.cabal
      paths:
        - wacc/.stack-work/
      policy: $BUILD_CACHE_POLICY

lint:
  image:
    entrypoint: [""]
    name: ghcr.io/danieljtrowbridge/docker-fourmolu:9.6.4
  script:
    - fourmolu --mode check wacc
  stage: lint

build:
  script:
    - stack build --test --no-run-tests
  stage: build
  variables:
    BUILD_CACHE_POLICY: 'pull-push'
  extends: .stack-cache

integration-test:
  script:
    - make integration-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  extends: .stack-cache

unit-test:
  script:
    - make unit-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  extends: .stack-cache

golden-test:
  script:
    - make golden-test
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  extends: .stack-cache
