workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - build
  - lint
  - test

default:
  image: haskell:9.6.3

build:
  artifacts:
    paths:
      - compile
  needs: []
  script:
    - make
  stage: build
  cache:
    - key:
        files:
          - stack.yml
          - stack.yml.lock
      paths:
        - .stack-work/
        - ~/.stack/
    - key:
        files:
          - wacc/package.yaml
          - wacc/wacc.cabal
      paths:
        - wacc/.stack-work/

lint:
  image:
    entrypoint: [""]
    name: ghcr.io/danieljtrowbridge/docker-fourmolu:9.6.4
  needs: []
  script:
    - fourmolu --mode check wacc
  stage: lint

integration-test:
  needs:
    - artifacts: false
      job: build
  script:
    - make check
  stage: test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
  cache:
    - key:
        files:
          - stack.yml
          - stack.yml.lock
      paths:
        - .stack-work/
        - ~/.stack/
    - key:
        files:
          - wacc/package.yaml
          - wacc/wacc.cabal
      paths:
        - wacc/.stack-work/
