resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/7.yaml

packages:
  - wacc/

extra-deps:
  - lib/gigaparsec

compiler: ghc-9.6.3
# Use system ghc to speed up CI
system-ghc: true
