name: wacc
version: 0.1.0.0
author:
  - Daniel Trowbridge <dt222@ic.ac.uk>
  - Manav Sankriti <ms3822@ic.ac.uk>
  - Junrong Chen <jc4922@ic.ac.uk>
  - Edwin Fernando <ef322@ic.ac.uk>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - dlist
  - gigaparsec
  - recursion-schemes
  - transformers
  - extra
  - filepath
  - cmdargs

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-missing-export-lists
  - -Wno-type-equality-requires-operators
  - -Wno-orphans
  - -j

library:
  source-dirs: src

executables:
  compile:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wacc

tests:
  wacc-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -F -pgmF=tasty-autocollect
    build-tools:
      - tasty-autocollect:tasty-autocollect
    dependencies:
      - generic-arbitrary
      - tasty
      - tasty-autocollect
      - tasty-hspec
      - tasty-hunit
      - tasty-quickcheck
      - tasty-hunit
      - tasty-golden
      - tasty-expected-failure
      - wacc
      - deepseq
      - directory
      - process
      - QuickCheck
      - bytestring
      - utf8-string
      - tagged
      - generic-deriving
      - stm
      - xml